export const reslist= [
    {
      id: "394784",
      name: "Theobroma",
      cloudinaryImageId: "63dd75492c47fcec191132b8eb299ea5",
      locality: "Shivaji Nagar",
      areaName: "Shivaji Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["Bakery", "Desserts"],
      avgRating: 4.6,
      parentId: "1040",
      avgRatingString: "4.6",
      totalRatingsString: "1K+",
      promoted: true,
      adTrackingId:
        "cid=13730973~p=1~adgrpid=13730973#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=394784~eid=4bb4fc34-934a-446a-aabd-07baf50d542e~srvts=1716960279620~collid=45995",
    },
    {
      id: "7887",
      name: "Priya",
      cloudinaryImageId: "pawz87ibiatpceg5uvpa",
      locality: "MG Road",
      areaName: "Camp",
      costForTwo: "₹250 for two",
      cuisines: ["South Indian", "Beverages"],
      avgRating: 4.5,
      parentId: "161324",
      avgRatingString: "4.5",
      totalRatingsString: "10K+",
    },
    {
      id: "17809",
      name: "Niranjan Veg Restaurant",
      cloudinaryImageId: "so4ctxrjbexl20tlx4qh",
      locality: "shivaji nagar pune",
      areaName: "Mahabaleshwar",
      costForTwo: "₹400 for two",
      cuisines: [
        "South Indian",
        "Maharashtrian",
        "Chinese",
        "Fast Food",
        "Beverages",
      ],
      avgRating: 4.3,
      parentId: "149197",
      avgRatingString: "4.3",
      totalRatingsString: "5K+",
    },
    {
      id: "434066",
      name: "Roopali Restaurant",
      cloudinaryImageId: "ngmsdg7jvwbbg1rmxze7",
      locality: "F.C. Road",
      areaName: "F.C. Road",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian", "North Indian", "Beverages"],
      avgRating: 4.6,
      parentId: "261543",
      avgRatingString: "4.6",
      totalRatingsString: "1K+",
    },
    {
      id: "13907",
      name: "Wadeshwar",
      cloudinaryImageId: "zsws4cdkzx90k3mlwozb",
      locality: "Erandwane",
      areaName: "Erandwane",
      costForTwo: "₹350 for two",
      cuisines: [
        "South Indian",
        "Snacks",
        "Street Food",
        "Beverages",
        "Desserts",
      ],
      avgRating: 4.6,
      parentId: "1770",
      avgRatingString: "4.6",
      totalRatingsString: "10K+",
    },
    {
      id: "65657",
      name: "Santosh Bakery",
      cloudinaryImageId: "n96b9ibni4es6jeymmdq",
      areaName: "Shivaji Nagar",
      costForTwo: "₹100 for two",
      cuisines: ["Bakery"],
      avgRating: 4.7,
      parentId: "177668",
      avgRatingString: "4.7",
      totalRatingsString: "1K+",
    },
    {
      id: "7855",
      name: "Supriya Restaurant",
      cloudinaryImageId: "ltjsyvudeyfnzmxttpxf",
      locality: "Camp",
      areaName: "Camp Area",
      costForTwo: "₹300 for two",
      cuisines: [
        "North Indian",
        "Chinese",
        "South Indian",
        "Fast Food",
        "Beverages",
        "Snacks",
      ],
      avgRating: 4.6,
      parentId: "197633",
      avgRatingString: "4.6",
      totalRatingsString: "10K+",
    },
    {
      id: "438162",
      name: "Gokhales Kitchen",
      cloudinaryImageId: "aokllwrug5o5w4as5wqq",
      locality: "Major Kg Pawar Road",
      areaName: "Karve Nagar",
      costForTwo: "₹200 for two",
      cuisines: ["Thalis", "Street Food", "South Indian", "Maharashtrian"],
      avgRating: 4.3,
      veg: true,
      parentId: "264293",
      avgRatingString: "4.3",
      totalRatingsString: "1K+",
    },
    {
      id: "39102",
      name: "Dadu's Sweet Emporio",
      cloudinaryImageId: "kpurefwytowa7128qlqm",
      locality: "Camp",
      areaName: "Camp Area",
      costForTwo: "₹600 for two",
      cuisines: ["Sweets", "Desserts", "Snacks", "Bakery"],
      avgRating: 4.6,
      parentId: "5789",
      avgRatingString: "4.6",
      totalRatingsString: "5K+",
      promoted: true,
      adTrackingId:
        "cid=13791155~p=4~adgrpid=13791155#ag1~mp=SWIGGY_IN~bl=FOOD~aet=RESTAURANT~aeid=39102~eid=274894aa-5ea8-4eab-8ece-c16e3167845a~srvts=1716960279620~collid=45995",
    },
    {
      id: "5496",
      name: "Marz O Rin",
      cloudinaryImageId: "ybwcl6ielgmogvrwqmjh",
      locality: "Camp",
      areaName: "Camp",
      costForTwo: "₹450 for two",
      cuisines: ["Bakery", "Beverages", "Snacks", "Desserts"],
      avgRating: 4.6,
      parentId: "132908",
      avgRatingString: "4.6",
      totalRatingsString: "10K+",
    },
    {
      id: "79046",
      name: "Appa",
      cloudinaryImageId: "py9pxc4jlk2ubkmphaix",
      locality: "Deccan Gymkhana",
      areaName: "Deccan Gymkhana",
      costForTwo: "₹150 for two",
      cuisines: ["Street Food"],
      avgRating: 4.6,
      parentId: "12028",
      avgRatingString: "4.6",
      totalRatingsString: "1K+",
    },
    {
      id: "116825",
      name: "Shri Chaturshringi mata Snacks center",
      cloudinaryImageId: "y32onxpod1xt5ef1gwjj",
      locality: "Paud Phata Road",
      areaName: "Kothrud",
      costForTwo: "₹200 for two",
      cuisines: ["Indian"],
      avgRating: 4.2,
      veg: true,
      parentId: "186315",
      avgRatingString: "4.2",
      totalRatingsString: "10K+",
    },
    {
      id: "11887",
      name: "Samudra Veg",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/5/6/d0807ef7-cc68-4cca-8032-c9eb44c9925e_11887.jpg",
      locality: "Erandwane",
      areaName: "Erandwane",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "South Indian"],
      avgRating: 4.5,
      parentId: "176775",
      avgRatingString: "4.5",
      totalRatingsString: "10K+",
      promoted: true,
    },
    {
      id: "64313",
      name: "Bedekar Misal",
      cloudinaryImageId: "s7iaru1tltotpdqnk8fa",
      locality: "Narayan Peth",
      areaName: "Narayan Peth",
      costForTwo: "₹400 for two",
      cuisines: ["Maharashtrian"],
      avgRating: 4.6,
      parentId: "42915",
      avgRatingString: "4.6",
      totalRatingsString: "10K+",
    },
    {
      id: "571805",
      name: "Udupi Bhavan",
      cloudinaryImageId: "xtjbziytzhxrnopxcg4b",
      locality: "Mayur Colony",
      areaName: "Kothrud",
      costForTwo: "₹300 for two",
      cuisines: ["South Indian"],
      avgRating: 4.2,
      veg: true,
      parentId: "13247",
      avgRatingString: "4.2",
      totalRatingsString: "100+",
    },
    {
      id: "803512",
      name: "Third Wave Coffee",
      cloudinaryImageId: "918a5f4ffad984f640d5c2d6961addd4",
      locality: "Bhamburda Village",
      areaName: "FC Road",
      costForTwo: "₹400 for two",
      cuisines: ["Beverages", "Bakery", "Continental"],
      avgRating: 4.5,
      parentId: "274773",
      avgRatingString: "4.5",
      totalRatingsString: "50+",
    },
  ];